server {
    listen 80;
    server_name _;

    # Angular-сборка.
    root /var/www/frontend;
    index index.html;

    client_max_body_size 32M;

    # API (CodeIgniter 4)
    # Все запросы, начинающиеся с /api, уходят в CI4.
    # CI4 будет знать про префикс /api и роуты будем объявлять с ним.
    location ~ ^/api(/|$) {
        include fastcgi_params;
        fastcgi_pass php:9000;

        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/index.php;
        fastcgi_param SCRIPT_NAME     /index.php;
        fastcgi_param DOCUMENT_ROOT   /var/www/backend/public;
    }

    # SPA (Angular)
    location / {
        try_files $uri $uri/ /index.html;
    }
}